const strings = {
  emailPlaceholderText: 'johndoe@gmail.com',
  namePlaceholderText: 'John Doe',
  passwordPlaceholderText: 'Enter your password',
  confirmPasswordPlaceholderText: 'Confirm your password',
  fullNameSubHeading: 'Full Name',
  emailSubHeading: 'Email',
  passwordSubHeading: 'Password',
  confirmPasswordSubHeading: 'Confirm Password',
  register: 'Register',
  termsAndConditions: 'Terms & Conditions',
  and: 'and',
  privacyPolicy: 'Privacy Policy',
  registeringWithAppHeadline: 'By registering you agree to our',
  facebook: 'Facebook',
  google: 'Google',
  forgotPassword: 'Forgot Password?',
  editEmailAddress: 'Edit Email Address',
  login: 'Login',
  whereYourCentsMakeSense: 'Where your cents make sense',
  dontHaveAnAccount: 'Don\'t have an account?',
  registerNow: 'Register Now.',
  welcomeLogin: 'LOGIN',
  welcomeSignUp: 'SIGN UP',
  checkYourEmail: 'Check your Email',
  resetLinkSent: 'We have sent you a reset password link on your registered email address.',
  goToEmail: 'Go To Email',
  viewInventory: 'View Inventory',
  editItems: 'Edit Items',
  addItems: 'Add Items',
  viewClients: 'View Clients',
  iAmA: 'I am a',
  iOwnA:'I own a',
  iRunA: 'I run a',
  supplier: 'Supplier',
  restaurant: 'Restaurant',
  loading: 'Loading, please wait...',
  edit: 'Edit',
  inventoryTypeText: 'Inventory type ',
  inventoryTypeSubheading: 'Inventory Type',
  inventoryName: 'Inventory Name',
  inventoryNamePlaceholderText: 'Add inventory name',
  inventoryQuantityAvailable: 'Quantity Available',
  inventoryQuantityAvailablePlaceholderText: 'Enter the quantity',
  inventoryPricePerUnit: 'Price per Unit',
  inventoryPricePerUnitPlaceholderText: 'Enter price per unit',
  addInventoryText: 'Add Inventory',
  inventoryDocumentName: 'Inventory Title',
  inventoryDocumentCategory: 'Item Category',
  inventoryDocumentUnit: 'Unit',
  inventoryDocumentNamePlaceholderText: 'Add an Item Title',
  inventoryUploadImage: 'Upload Image',
  nameCannotBeEmpty: 'Name cannot be empty',
  emailCannotBeEmpty: 'Email cannot be empty',
  passwordCannotBeEmpty: 'Password cannot be empty',
  confirmPasswordCannotBeEmpty: 'Either passwords cannot be empty',
  passwordsDoNotMatch: 'Passwords do not match',
  nameErrorMessage: 'Please enter your full name with no special characters.',
  emailErrorMessage: 'Please enter a properly formatted email address.',
  passwordErrorMessage: 'Password must have at least 6 characters',
  inventoryTitleCannotBeEmpty: 'Inventory title cannot be empty',
  inventoryCategoryCannotBeEmpty: 'Inventory category cannot be empty',
  pricePerUnitCannotBeEmpty: 'Price per unit cannot be empty',
  pricePerUnitErrorMessage: 'Price per unit has to be a number.',
  pleaseChooseCategory: 'Please choose/type category',
  pleaseChooseUnit: 'Please choose/type unit',
  pleaseTryAgain: 'Please try again!',
  enterYourEmailForgotPassword: 'Enter the email used for registration : ',
  sendEmail: 'Send Email',
  sorryWeNeedPermissions: 'Sorry, we need camera roll permissions to make this work!',
  chooseUploadImageOption: 'Choose Image Upload Option',
  inventoryUnitCannotBeEmpty: 'Inventory unit cannot be empty',
  addressHeading: 'Pick Address',
  addressSubHeading: 'Type your address or choose your current location',
  enterAddress: 'Touch to enter address',
  addressPlaceholder: 'Type here...',
  chooseCurrentLocation: 'Use Current Location',
  or: 'or',
  addressModalSubheading: 'Enter your address',
  close: 'Close',
  cancel: 'Cancel',
  submit: 'Submit',
  registeredEmail: 'Registered Email',
  pleaseProvideThis: 'Please provide this.',
  signOut: 'Sign Out',
  phoneNumber: 'Phone Number',
  choosePhoneExtension: 'Choose phone extension',
  enterPhone: 'Enter Phone',
  searchItems: 'Search Items',
  editYourItemsBelow: 'Edit your items below',
  viewYourItemsBelow: 'View your items below',
  inventory: 'Inventory',
  viewOrders: 'View Orders',
  addSupplier: 'Add Supplier',
  address: 'Address',
  phone: 'Phone',
  enterNewEmail: 'Enter new email address:',
  confirmEmail: 'Confirm Email',
  viewSuppliers: 'View Suppliers',
  viewYourClientsBelow: 'View your Clients Below: ',
  viewYourSuppliersBelow: 'View your Suppliers Below: ',
  orders: 'Orders',
  viewYourOrdersBelow: 'View your orders below',
  chooseASupplierToAdd: 'Choose a Supplier to Add: ',
  suppliers: 'Suppliers',
  itemToOrder: 'Items',
  findTheItemsToOrderBelow: 'Find the items to order below',
  yourOrder: 'Your Order',
  findYourOrderBelow: 'Find your order below: ',
  registerWithUs: 'Register With Us',
  iWantTo: 'I want to',
  help: 'Help',
  ngo: 'NGO'
}

export default strings
